### ISSUE TITLE
Python3で動作するように変更

### ISSUE THREAD

**Issue by tadaken3** [karaage0703/post-hatena#2]
こちらのコードをベースにPython3でも動くように改良致しました。
大変参考になりました。ありがとうございます。

https://github.com/tadaken3/hatenablog_post

**Comment by karaage0703** [comment]
ありがとうございます。ブログも拝見しました。
私の方も、python3にも対応したいなと思いますので、こちらこそ参考にさせて下さい。
一応英語ではPython3で投稿できるようにできたのですが、日本語だとエンコーディングの関係でエラーが出ています。日本語の扱い中々大変ですね。

**Comment by tadaken3** [comment]
こちらこそ、ブログでご紹介いただきありがとうございます！

Python2と3で文字列の扱い方が異なるので、日本語の場合はちょっと厄介ですよね。
ブログの読者登録もありがとうございます！
